version: "3.9"
services:
  manager:
    image: 'swr.cn-east-3.myhuaweicloud.com/ruilisi-leo/color-ball-web'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:3000"
    depends_on:
      # - server
  # server:
  #   image: 'hkccr.ccs.tencentyun.com/swarmbee/beevpn-server:v0'
  #   environment:
  #     ALLOWED_IPS: "0.0.0.0"
  #     DATABASE_URL:       
  #     DEVISE_JWT_SECRET_KEY:       
  #     RACK_ENV: production
  #     RAILS_ENV: production
  #     REDIS_URL: redis://redis/0
  #     REDIS_CACHE_STORE_URL: redis://redis/1
  #     SECRET_KEY_BASE: 
  #     SECRET_TOKEN: 
  #   depends_on:
  #     - postgres
  #     - redis
  # postgres:
  #   image: 'postgres:14-alpine'
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 
  #     POSTGRES_DB: beevpn_production
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  # redis:
  #   image: 'redis:alpine'
  #   volumes:
  #     - ./redis:/data
